name: bug_tracker
services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_SERVER=${DATABASE_SERVER}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: > 
      bash -c "python ./bug_tracker/manage.py wait_for_db &&
               python ./bug_tracker/manage.py migrate &&
               python ./bug_tracker/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data: