name: bug_tracker
services:
  db:
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
  web:
    build:
      args:
        INSTALL_DEV: false
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py wait_for_db &&
               python manage.py migrate &&
               gunicorn bug_tracker.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
  nginx:
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl/bugtracker.crt:/etc/ssl/certs/bugtracker.crt:ro
      - ./docker/nginx/ssl/bugtracker.key:/etc/ssl/private/bugtracker.key:ro
    ports:
      - "80:80"
      - "443:443"
  redis:
    volumes:
      - redis-data-prod:/data
    env_file:
      - .env.prod
  celery:
    env_file:
      - .env.prod
  flower:
    env_file:
      - .env.prod
volumes:
  db-data-prod:
  redis-data-prod:
