# Generated by Django 5.1.6 on 2025-03-01 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectidentifier",
            options={"verbose_name": "Project identifier", "verbose_name_plural": "Project identifiers"},
        ),
        migrations.AlterModelOptions(
            name="projectroleassignment",
            options={"verbose_name": "Project role assignment", "verbose_name_plural": "Project role assignments"},
        ),
        migrations.AddField(
            model_name="projectidentifier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectroleassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectroleassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(choices=[(1, "active"), (2, "closed")], default=1),
        ),
    ]
